### ISSUE TITLE
Add support for adding labels (ids) to steps

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/ecmarkdown#56]
Needed to avoid <https://github.com/tc39/ecma262/pull/1835> from happening again.

## Proposed syntax:

Allow `<label_name>:` in ordered lists, where `<label_name>` matches the regular expression:

```
^[a-zA-Z_$][a-zA-Z0-9_$]*$
```

## Example:

```html
<emu-clause id="sec-assertfoo" aoid="AssertFoo">
	<h1>AssertFoo( _val_ )</h1>

	<p>The AssertFoo algorithm ensures that _val_ is an object with an [[IsFoo]] internal slot, by only returning in <emu-xref aoid="AssertFoo" step="Is_Foo_$1"></emu-xref>.</p>

	<emu-alg>
		1. Assert: Type(_val_) is Object.
		1. If ? _val_.[[IsFoo]] is *true*
			Is_Foo_$1:
			1. Return _val_
		1. Throw a *TypeError* exception.
	</emu-alg>
</emu-clause>
```

`[step Is_Foo_$1]` would be replaced with an anchor link linking to the labeled step with the **HTML** <code>step&amp;nbsp;<var>${num}</var></code>, where `${num}` is the number of the step.

## See also:
- https://github.com/tc39/ecmarkup/issues/192

**Comment by ljharb** [comment]
Would this work with a step used anywhere in the entire document? if so, perhaps it should be namespaced under the name of the abstract operation?

**Comment by bakkot** [comment]
I went with a slightly different syntax in https://github.com/tc39/ecmarkdown/pull/74: `1. [label="foo"] Step.` I didn't namespace them because emcarkup doesn't really have a notion of the abstract operation associated with an algorithm; algorithm steps can appear wherever.

**Comment by ljharb** [comment]
Does that mean the label must be unique across the whole document?

**Comment by bakkot** [comment]
Yup.
