### ISSUE TITLE
Consider dropping support for full documents

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkdown#64]
Currently this project exports a function for processing a full document, and does not export functions for processing anything else. The last release had functions for processing both full documents and fragments.

But the canonical way to process a full document is with [ecmarkup](https://github.com/tc39/ecmarkup/), and ecmarkup only uses this project for processing fragments (like `<p>in _this |Example|</p>`) and algorithms. It might make sense to have exports for exactly those cases, and nothing else.

**Comment by bakkot** [comment]
cc @rbuckton: you're the only person I can think of who might be relying on parsing whole documents with this project. Are you? Are you aware of anyone else who might be? If not I think I'm going to go ahead with this, to simplify maintenance burden.

**Comment by rbuckton** [comment]
I'll take a look at this, as well as anything I'm doing to consume it, sometime tonight.
