### ISSUE TITLE
Tag new Version

### ISSUE THREAD

**Issue by vivekkj123** [tc39/ecmarkdown#83]
Hi there, 
           Please tag the npm version (i.e. **6.0.0**) of this module in this upstream repo.. we want to pack this awesome npm module to debian, so please do as soon as possible,

Regards,
VIVEK K J
www.vivekkj.me
Debian Community

**Comment by bakkot** [comment]
[Done.](https://github.com/tc39/ecmarkdown/tree/v6.0.0)

**Comment by vivekkj123** [comment]
Please re-tag the version because of I made a minor change in #85 ..
